replicas:
 __metadata:
    name: "replicas"
    label: "Number of replicas"
    description: "The number of desired replica pods that run simultaneously."
    type: "number"
    default: 1
    immutable: false
    required: true

debugMode:
 __metadata:
    name: "debugMode"
    label: "Debug Mode"
    description: "Enables highest logging level"
    type: "boolean"
    default: false
    immutable: false
    required: true

watsonskill:
  __metadata:
    label: "Watson skill access"
  assistantUsername:
    __metadata:
      name: "assistantUsername"
      label: "Watson Assistant Instance Username"
      description: "The user name used to authenticate to Watson Assistant"
      type: "string"
      default: "apikey"
      immutable: false
      required: true
  assistantPassword:
    __metadata:
      name: "assistantPassword"
      label: "Watson Assistant Instance Password"
      description: "The password used to authenticate to Watson Assistant"
      type: "string"
      default: "V5TQ7K7bEHSP6kafKUHvd50I5-_q5F434adalHPKrAa1"
      immutable: false
      required: true
  workspaceId:
    __metadata:
      name: "workspaceId"
      label: "Watson Assistant Workspace ID"
      description: "The Workspace ID of the Watson skill integrated with Slack"
      type: "string"
      immutable: false
      default: "4accc957-376d-4fdf-b2d4-496249c0c5e6"
      required: true
  assistantUrl:
    __metadata:
      name: "assistantUrl"
      label: "Watson Assistant API Endpoint"
      description: "REST endpoint used to interact with the Watson Assistant skill"
      type: "string"
      default: "https://gateway.watsonplatform.net/assistant/api"
      immutable: false
      required: false
