replicas:
 __metadata:
    name: "replicas"
    label: "Number of replicas"
    description: "The number of desired replica pods that run simultaneously."
    type: "number"
    default: 1
    immutable: false
    required: true

debugMode:
 __metadata:
    name: "debugMode"
    label: "Debug Mode"
    description: "Enables highest logging level"
    type: "boolean"
    default: false
    immutable: false
    required: true

watsonskill:
  __metadata:
    label: "Watson skill access"
  assistantIamApiKey:
    __metadata:
      name: "assistantIamApiKey"
      label: "Watson Assistant Instance IAM API Key"
      description: "The API key used for authentication"
      type: "string"
      immutable: false
      required: true
  workspaceId:
    __metadata:
      name: "workspaceId"
      label: "Watson Assistant Workspace ID"
      description: "The Workspace ID of the Watson skill"
      type: "string"
      immutable: false
      required: true
  assistantUrl:
    __metadata:
      name: "assistantUrl"
      label: "Watson Assistant API Endpoint"
      description: "REST endpoint for Watson Assistant"
      type: "string"
      immutable: false
      required: true
