apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: assistantsimple
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name | quote }}


spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
         app: assistantsimple
         chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
         release: {{ .Release.Name | quote }}


    spec:
      containers:
      - name: {{ .Release.Name }}-web
        image: {{ .Values.service.image }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: {{ .Values.service.containerPort }}
        env:
        - name: DEBUG_MODE
          value: "{{ .Values.debugMode }}"
        - name: ASSISTANT_USERNAME
          value: {{ .Values.watsonskill.assistantUsername }}
        - name: ASSISTANT_PASSWORD
          value: {{ .Values.watsonskill.assistantPassword }}
        - name: WORKSPACE_ID
          value: {{ .Values.watsonskill.workspaceId }}
        - name: ASSISTANT_URL
          value: "{{ .Values.watsonskill.assistantUrl }}"
