apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: "{{  .Chart.Name }}-application-service"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.containerPort }}
{{ if (.Values.service.type) and eq .Values.service.type "NodePort" and (.Values.service.nodePort) }}
    nodePort: {{ .Values.service.nodePort }}
{{ end }}

  selector:
    app: "{{  .Chart.Name }}-selector"
